sudo: required
services:
        - docker

before_install:
        - docker build -t tjengland1024/docker-react -f Dockerfile.dev .

script:
        - docker run tjengland1024/docker-react npm run test -- --coverage
